# Generated by Django 5.1.5 on 2025-02-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_position_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='additional_costs',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
