# Generated by Django 5.1.5 on 2025-02-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_worklog_additional_costs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='additional_costs',
        ),
        migrations.AddField(
            model_name='project',
            name='additional_costs',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True),
        ),
    ]
